# Generated by Django 4.2.7 on 2023-11-22 18:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, verbose_name=[django.core.validators.EmailValidator(message='Enter a valid email address.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
